
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'inicioCADENA CLASS COMILLA IDENTIFICADOR LLAVEDER LLAVEIZQ MAIN NAMESPACE PARDER PARIZQ PUNTO STATIC USING VOID WRITE_LINEinicio : using_directiva namespaceusing_directiva : USING IDENTIFICADOR PUNTO IDENTIFICADOR PUNTOnamespace : NAMESPACE IDENTIFICADOR LLAVEIZQ bloque LLAVEDERbloque : declaracion_clasedeclaracion_clase : CLASS IDENTIFICADOR LLAVEIZQ bloque_main LLAVEDERbloque_main : declaracion_maindeclaracion_main : STATIC VOID MAIN PARIZQ IDENTIFICADOR PARDER bloque_instruccionbloque_instruccion : LLAVEIZQ instruccion LLAVEDERinstruccion : IDENTIFICADOR PUNTO WRITE_LINE PARIZQ CADENA PARDER PUNTO'
    
_lr_action_items = {'USING':([0,],[3,]),'$end':([1,4,15,],[0,-1,-3,]),'NAMESPACE':([2,14,],[5,-2,]),'IDENTIFICADOR':([3,5,8,13,24,28,],[6,7,10,16,25,30,]),'PUNTO':([6,10,30,36,],[8,14,32,37,]),'LLAVEIZQ':([7,16,26,],[9,17,28,]),'CLASS':([9,],[13,]),'LLAVEDER':([11,12,18,19,21,27,29,31,37,],[15,-4,21,-6,-5,-7,31,-8,-9,]),'STATIC':([17,],[20,]),'VOID':([20,],[22,]),'MAIN':([22,],[23,]),'PARIZQ':([23,33,],[24,34,]),'PARDER':([25,35,],[26,36,]),'WRITE_LINE':([32,],[33,]),'CADENA':([34,],[35,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'inicio':([0,],[1,]),'using_directiva':([0,],[2,]),'namespace':([2,],[4,]),'bloque':([9,],[11,]),'declaracion_clase':([9,],[12,]),'bloque_main':([17,],[18,]),'declaracion_main':([17,],[19,]),'bloque_instruccion':([26,],[27,]),'instruccion':([28,],[29,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> inicio","S'",1,None,None,None),
  ('inicio -> using_directiva namespace','inicio',2,'p_inicio','app.py',92),
  ('using_directiva -> USING IDENTIFICADOR PUNTO IDENTIFICADOR PUNTO','using_directiva',5,'p_using_directiva','app.py',96),
  ('namespace -> NAMESPACE IDENTIFICADOR LLAVEIZQ bloque LLAVEDER','namespace',5,'p_namespace','app.py',100),
  ('bloque -> declaracion_clase','bloque',1,'p_bloque','app.py',104),
  ('declaracion_clase -> CLASS IDENTIFICADOR LLAVEIZQ bloque_main LLAVEDER','declaracion_clase',5,'p_declaracion_clase','app.py',108),
  ('bloque_main -> declaracion_main','bloque_main',1,'p_bloque_main','app.py',112),
  ('declaracion_main -> STATIC VOID MAIN PARIZQ IDENTIFICADOR PARDER bloque_instruccion','declaracion_main',7,'p_declaracion_main','app.py',116),
  ('bloque_instruccion -> LLAVEIZQ instruccion LLAVEDER','bloque_instruccion',3,'p_bloque_instruccion','app.py',120),
  ('instruccion -> IDENTIFICADOR PUNTO WRITE_LINE PARIZQ CADENA PARDER PUNTO','instruccion',7,'p_instruccion','app.py',124),
]
